import html as _html
from abc import ABC, abstractmethod
from datetime import date as _date

import pandas as pd
from loguru import logger

from arxivrec.dataset.fetcher import BaseFetcher
from arxivrec.engine.encoder import TextEncoder
from arxivrec.engine.ranker import BaseRanker
from arxivrec.notify.notification import BaseNotifier, EmailNotifier
from arxivrec.topic import Topic

_TOPIC_COLORS = ["#0891b2", "#7c3aed", "#f59e0b", "#10b981", "#ef4444"]

_DIGEST_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
  background:#eef2f7;color:#1a202c;padding:24px 16px}}
.wrap{{max-width:680px;margin:0 auto}}
.hdr{{background:linear-gradient(135deg,#1e1b4b,#4338ca);
  border-radius:14px 14px 0 0;padding:32px 36px;color:#fff}}
.hdr h1{{font-size:20px;font-weight:700;margin-bottom:10px}}
.hdr-meta{{font-size:12px;color:rgba(255,255,255,.65);display:flex;gap:10px;align-items:center}}
.chip{{background:rgba(255,255,255,.18);padding:3px 11px;
  border-radius:20px;font-size:11.5px}}
.sec{{background:#fff;margin-top:2px;padding:26px 32px}}
.sec:last-of-type{{border-radius:0 0 14px 14px}}
.sec-hdr{{display:flex;align-items:center;gap:9px;padding-bottom:14px;
  border-bottom:1px solid #e8edf3;margin-bottom:18px}}
.dot{{width:9px;height:9px;border-radius:50%;flex-shrink:0}}
.sec-title{{font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.9px;color:#64748b}}
.cnt{{margin-left:auto;font-size:11px;color:#94a3b8}}
.paper{{padding:15px 0;border-bottom:1px solid #f1f5f9}}
.paper:last-child{{border-bottom:none;padding-bottom:0}}
.ptitle a{{font-size:14px;font-weight:600;color:#0f172a;
  text-decoration:none;line-height:1.45}}
.ptitle a:hover{{text-decoration:underline}}
.authors{{font-size:11.5px;color:#94a3b8;margin:4px 0 9px}}
.reason{{font-size:12.5px;color:#334155;line-height:1.65;background:#f8fafc;
  border-left:3px solid;padding:9px 13px;border-radius:0 5px 5px 0}}
.plink{{display:inline-block;margin-top:7px;font-size:11px;color:#94a3b8;text-decoration:none}}
.plink:hover{{color:#64748b}}
.foot{{text-align:center;font-size:11px;color:#94a3b8;margin-top:18px;padding:8px}}
</style>
</head>
<body>
<div class="wrap">
<div class="hdr">
  <h1>📚 ArXiv Daily Digest</h1>
  <div class="hdr-meta">
    <span>{date}</span>
    <span class="chip">{total_papers} papers</span>
    <span class="chip">{num_topics} topics</span>
  </div>
</div>
{sections}
<div class="foot">Generated by <b>arxivrec</b></div>
</div>
</body>
</html>"""


def build_digest_html(topics: list[Topic], results: dict[str, pd.DataFrame]) -> str:
    today = _date.today().strftime("%B %-d, %Y")
    total = sum(len(df) for df in results.values() if df is not None and not df.empty)
    num_topics = sum(
        1 for t in topics if results.get(t.id) is not None and not results[t.id].empty
    )

    sections = ""
    for i, topic in enumerate(topics):
        df = results.get(topic.id)
        if df is None or df.empty:
            continue

        color = _TOPIC_COLORS[i % len(_TOPIC_COLORS)]
        label = _html.escape(topic.id.replace("_", " "))
        papers_html = ""

        for _, row in df.iterrows():
            title = _html.escape(str(row["title"]))
            authors = _html.escape(str(row["authors"]))
            reason = _html.escape(str(row["reasoning"]))
            url = _html.escape(str(row["url"]))
            arxiv_id = str(row["id"]).split("v")[0]

            papers_html += (
                f'<div class="paper">'
                f'<div class="ptitle"><a href="{url}" target="_blank">{title}</a></div>'
                f'<div class="authors">{authors}</div>'
                f'<div class="reason" style="border-color:{color}">{reason}</div>'
                f'<a class="plink" href="{url}" target="_blank">'
                f"→ arxiv.org/abs/{arxiv_id}</a>"
                f"</div>"
            )

        sections += (
            f'<div class="sec">'
            f'<div class="sec-hdr">'
            f'<div class="dot" style="background:{color}"></div>'
            f'<span class="sec-title">{label}</span>'
            f'<span class="cnt">{len(df)} papers</span>'
            f"</div>"
            f"{papers_html}"
            f"</div>"
        )

    return _DIGEST_TEMPLATE.format(
        date=today,
        total_papers=total,
        num_topics=num_topics,
        sections=sections,
    )


class EmptyFetchException(Exception):
    """No fetch result!"""

    pass


class EmailFailException(Exception):
    """Fail to send email!"""

    pass


class BasePipeline(ABC):
    def __init__(self, topic: Topic, **kwargs):
        self.topic = topic

    @abstractmethod
    def recommend(self) -> pd.DataFrame:
        pass

    @abstractmethod
    def notify(self) -> None:
        pass


class LLMPipeline(BasePipeline):
    def __init__(
        self,
        topic: Topic,
        simsearch_top_k: int,
        fetcher: BaseFetcher,
        encoder: TextEncoder,
        llm_ranker: BaseRanker,
        notifier_list: list[BaseNotifier],
    ):
        super().__init__(topic)
        self.simsearch_top_k = simsearch_top_k
        self.fetcher = fetcher
        self.encoder = encoder
        self.llm_ranker = llm_ranker
        self.df_recommendation: pd.DataFrame | None = None
        self.notifier_list = (
            notifier_list if notifier_list is not None else [EmailNotifier()]
        )

    def __repr__(self):
        return (
            f"{self.__class__.__name__}("
            f"topic='{self.topic}', "
            f"simsearch_top_k={self.simsearch_top_k}, "
            f"fetcher={self.fetcher}, "
            f"encoder={self.encoder}, "
            f"llm_ranker={self.llm_ranker}, "
            f"notifiers={self.notifier_list}"
            f")"
        )

    def recommend(self) -> pd.DataFrame:
        df = self.fetcher.fetch()

        if df is None or len(df) == 0:
            raise EmptyFetchException("No items fetched!!")

        logger.info("Start topic and content embedding...")

        my_interest_embedding = self.encoder.encode([self.topic.description])
        content_embedding = self.encoder.encode(df["combined_text"].tolist())
        top_k_indices = self.encoder.get_top_k_similar(
            my_interest_embedding, content_embedding, k=self.simsearch_top_k
        )
        df_simsearch = df.iloc[top_k_indices]

        logger.info("Similarity search done!")

        self.df_recommendation = self.llm_ranker.rank(
            self.topic.description, df_simsearch
        )

        if self.df_recommendation is not None:
            titles = self.df_recommendation["title"].tolist()
            logger.info(f"Recommended articles: {titles}")

        return self.df_recommendation

    def notify(self):
        if self.df_recommendation is None:
            raise EmailFailException("No recommendations available to notify about!")

        EMAIL_TEMPLATE = """
        <html>
        <body>
            <h2>Today's ArXiv Recommendations 🐈</h2>
            <p>Based on your interest: {my_interest}, here are the top 5 papers:</p>
            {input_html_table}
        </body>
        </html>
        """

        try:
            email_columns = ["title", "reasoning", "url"]
            html_table = self.df_recommendation[email_columns].to_html(
                index=False, render_links=True
            )

            email_full_body = EMAIL_TEMPLATE.format(
                my_interest=self.topic.description, input_html_table=html_table
            )

            for _notifier in self.notifier_list:
                _notifier.notify(
                    subject="📚 Your Daily ArXiv Digest", body_html=email_full_body
                )
                logger.info(f"{_notifier} notification sent successfully!")

        except Exception:
            raise EmailFailException("Failed to send email notification!")
